name: pyTSEB
channels:
    - conda-forge
dependencies:
    - python=3.10
    - gdal
    - numpy
    - scipy
    - pandas
    - jupyter
    - notebook
    - bokeh
    - netCDF4
    - pip
    - pip:
        - https://github.com/hectornieto/pypro4sail
